### ISSUE TITLE
Implement true markdown to XML conversion

### ISSUE THREAD

**Issue by PeterMosmans** [radicallyopensecurity/pentext#10]
The gitlab-to-pentext.py bridge currenly doesn't convert markdown syntax to proper XML tags. E.g. backticks to matching `<monospace>` tags.

TODO:
Add proper conversion for the most used tags

**Comment by PeterMosmans** [comment]
I ran a couple of tests with pypandoc, and that works great. However, this means that the current conversion  (jxmlease). jxmlease is the library which takes care of the conversion from object to XML, and as far as I tested that can't handle 'raw' XML

**Comment by khorben** [comment]
Some suggestions for conversion:
* unnumbered lists: `*` to &lt;ul>&lt;li>
* numbered lists: `1.` etc to &lt;ol>&lt;li>
* inline fixed-width fonts: `some text` to &lt;monospace>some text&lt;/monospace>
* links: `http://...` etc to &lt;a href="&">&&lt;/a>
* pre-formatted text: ``` to &lt;pre>&lt;monospace>
* source code: ```c, ```php etc to &lt;code> (backtick-backtick-backtick-language name)
* images: `! [Screenshot](path/to/img)` to &lt;img>

**Comment by khorben** [comment]
Looks promising: http://commonmark.org/.

**Comment by PeterMosmans** [comment]
The test version is working, I'll create a pull request soon...
Note that I'm using pandoc, writing parsers yourself is a recipe for disaster :wink:
