### ISSUE TITLE
Pipeline issue finding flagged as finding & non-finding

### ISSUE THREAD

**Issue by aphick** [radicallyopensecurity/pentext#110]
"I just fixed some pipeline problem where a finding was flagged as finding and as non-finding at the same time, which lead to a stacktrace about non-identical id's in the report. Which makes sense because the same id popped up in the finding section as well as the non-finding section. The pipeline has been fixed for now by removing one of the tags.

- [ ] We might want to create a check for this case in the `convert.py` script.

**Comment by PeterMosmans** [comment]
Hey @aphick - this sounds like an issue with the pentext _tooling_ , and not with pentext: `convert.py` is not part of this repository (anymore). Closing this issue
