### ISSUE TITLE
Do not lower-case finding types in "Findings by Type" summary

### ISSUE THREAD

**Issue by ros-cr** [radicallyopensecurity/pentext#138]
Pentext can generate a "Findings by Type" executive summary section with a pie chart on the left and a color-coded list of most common finding types on the right. 

In this list, Pentext incorrectly changes the casing of the types. They are forced to lowercase, except for the first character. I suspect this is done internally to better deduplicate finding types with slightly different casing, but the result deviates from what the authors intended and (in my opinion) harms readability.

For example, if `CWE-123: Write-what-where Condition` is used as a finding type, it would be expected to reproduce it as such, and not as `Cwe-123 write-what-where condition`.  This reproduction is also inconsistent with how it's rendered on the issue itself, as well as in other tables on the executive summary such as the summary of findings (second column "Type"), which keep the original (correct) casing.

Example screenshot from [a the public report](https://github.com/radicallyopensecurity/ros-website/blob/main/ros-public-reports/ROS%20-%20The%20Tauri%20Programme%20-2022.pdf): 

![pentext_type_handling_case_problem1](https://github.com/user-attachments/assets/b312a4d9-c8e5-4cee-8f6a-9b5d7fbf2f7f)

In this screenshot, the problem is not quite as visible due to the lack of all-uppercase acronyms, but shows as well - the original types in the report were upper-cased.

**Comment by PeterMosmans** [comment]
Will do, thanks for the reminder. It's on my list
