### ISSUE TITLE
Sort the creation of findings by arithmetic value

### ISSUE THREAD

**Issue by khorben** [radicallyopensecurity/pentext#15]
I have the impression that findings 20, 21, 22 for instance are converted before finding 3. If confirmed, it would make more sense for the initial conversion to match the order in which the findings were filed.

See also `sort(1)`, option `-n`.

**Comment by PeterMosmans** [comment]
Hi @khorben - why does the order of conversion/filing matter ? For pentest reports, personally I reshuffle the items based on impact, so that the order of _conversion_ / filing is irrelevant. I see it as an identifier, nothing more, nothing less... :wink:

**Comment by PeterMosmans** [comment]
Closing this issue
