### ISSUE TITLE
Validating multiple masters files masks results

### ISSUE THREAD

**Issue by gronke** [radicallyopensecurity/pentext#46]
The [validate_files method](https://github.com/radicallyopensecurity/pentext/blob/master/chatops/python/validate_report.py#L189) creates a list of `masters`, which is a list of top-level .xml files.

When multiple of those files were detected, only the last one is taken into account for the results, as seen here https://github.com/radicallyopensecurity/pentext/blob/master/chatops/python/validate_report.py#L218-219

**Comment by PeterMosmans** [comment]
Thanks for reporting, I'll add an OR selector for the result

**Comment by PeterMosmans** [comment]
On second look, it seems to be working ? The result is okay when True. For the result a boolean AND statement is used, so the result will only be True if all validations were successful.
Isn't this working as planned ? If not, could you please show / tell me an example how this would fail ?

Thanks!

Peter

**Comment by PeterMosmans** [comment]
@gronke is this still applicable ? If  not, I'll close this report. Thanks for letting me know !

**Comment by gronke** [comment]
@PeterMosmans yes it is. Here's a permalink to the current master:
https://github.com/radicallyopensecurity/pentext/blob/cf74247f868575591f083ea13948f3400b83f7a4/chatops/python/validate_report.py#L215=L216

**Comment by PeterMosmans** [comment]
Hi @gronke I'm a bit confused, as this seems to be working okay. The result (validation) is OK (true) if all validations were successful. If one fails along the way, then the result will be false. Am I missing something here ?
