### ISSUE TITLE
Use location from company details instead of using hardcoded "Amsterdam"

### ISSUE THREAD

**Issue by PeterMosmans** [radicallyopensecurity/pentext#55]
https://github.com/radicallyopensecurity/pentext/blob/6788dc9a2bcb2cf10c831b0a9c70caffe2acb415/xml/xslt/meta.xslt#L48

Most variables are configurable and are read from the 'configuration' XML files. The location is hardcoded.

Request: Read variable from company metadata

**Comment by syrosh** [comment]
Has since been fixed https://github.com/radicallyopensecurity/pentext/blob/master/xslt/meta.xslt#L89
