### ISSUE TITLE
Some wrong conversions in gitlab-to-pentext.py

### ISSUE THREAD

**Issue by skyanth** [radicallyopensecurity/pentext#58]
1. Subheaders get converted to `<h3>` but there is no `<h3>` in pentext (should be `<b>`)
2. Bold/Italic (dunno which) get converted to `<em>` but there is no `<em>` in pentext (should be `<b>` or `<i>`)
3. `<a>` elements get a `@class='url'` which doesn't exist in pentext
4. `<img>` should be its own block, not embedded in a `<p>`
5. triple backticks should be converted to `<pre>` not `<pre><code>`

**Comment by PeterMosmans** [comment]
Closed, as the conversion scripts have been removed from this repository
