### ISSUE TITLE
Converting from .fo to PDF

### ISSUE THREAD

**Issue by jeandoeshow** [radicallyopensecurity/pentext#70]
So I am currently trying to convert the .fo file I generated based on the xml in /sample-report/source/report.xml, but I am getting errors while converting the .fo to .pdf by using the following command:

./fop -c conf/rosfop.xconf /Users/<user>/pentestreport.fo /Users/<user>/Documents/pentestreport.pdf.

Overall this seems to work fine, until the following error message appears multiple times:

org.xml.sax.SAXParseException; systemId: file:/Users/jeanbeurskens/Documents/pentestreport.fo; lineNumber: 60; columnNumber: 349; XML document structures must start and end within the same entity.

Not sure if this a known issue, but I'm not sure what I am currently doing wrong. Installed all the things needed as mentioned in the tutorial, so not sure what is going wrong. Any idea what is going wrong? Running the script on MacOS.

**Comment by tweidinger** [comment]
In case this is still an issue. Could you add more description about what you have done explicitly?
I worked through the tutorial and could not reproduce this.

**Comment by syrosh** [comment]
Closing as stale. If still an issue please comment
