### ISSUE TITLE
Hardcoded external source dependencies

### ISSUE THREAD

**Issue by tweidinger** [radicallyopensecurity/pentext#73]
The editor folder contains all the _node_modules_ sources inside the folder already.
These should not be re-distributed by pentext and acquired by the user locally.
Aside from introducing outdated packages with security implications, we also face possible license issues here.

Suggestion would be to remove this folder, move the dependencies to the _package.json_ file and introduce a installation procedure in a _README.md_ file in the editor folder.
Also I am not sure if this folder is needed, due to the docmentation of the editor.

**Comment by PeterMosmans** [comment]
Closed, as the editor has been removed in version 2.0.0
