### ISSUE TITLE
Shell script bug?

### ISSUE THREAD

**Issue by Synchro** [radicallyopensecurity/pentext#77]
I think [this is a bug](https://github.com/radicallyopensecurity/pentext/blob/master/chatops/bash/handler_pentest#L153):

    [[ ! -z $PREVIOUS ]] && $REPO=$PREVIOUS

Should be (removed `$` from LHS of assignment):

    [[ ! -z $PREVIOUS ]] && REPO=$PREVIOUS

This could possibly make sense in PHP where you can have variable variables, but we're not there!

See [here](https://github.com/koalaman/shellcheck/wiki/SC1066);

**Comment by syrosh** [comment]
No longer an issue since chatops has been removed
